# workflow 名称
name: CI

on:
  # push 的时候触发
  push:
    branches: [ master ]
  # 每周二触发
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  # 获取照片 Job1
  social:
    timeout-minutes: 10
    # 服务器选择
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - uses: actions/checkout@v2
      
      # 设置 node 环境
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # 添加依赖
      - name: Install dependencies
        run: npm install

      # 生成文件
      - name: Generate README file
        run: node index.js

      # push 代码，需要自己的 Github token
      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.blog}}
        
  # 更新博客 Job2
  blog:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: social
    steps:
      - uses: actions/checkout@v2
      
      # 使用 docker compose 部署 rsshub
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install
          
      # 将注释替换成更新博客链接
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://localhost:1200/juejin/posts/1028798616188599"
          
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
