name: blog

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: blog
        uses: your-username/your-repository/.github/workflows/blog.yml@main
        with:
          blog_rss_link: https://shyblog.world/rss.xml
          blog_limit: 5
          brain_rss_link: https://shyblog.world/rss.xml
          brain_limit: 5
